## Spring properties
# Service registers under this name
spring:
  application:
    name: hello-client
    
server: 
  port: 9093   

eureka:
 client: #Not a client
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:9091/eureka/
    instance:
      hostname:localhost